version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql